# Base ROS 2 Humble on Ubuntu 22.04
ARG BASE_IMAGE=osrf/ros:jazzy-desktop-noble

FROM ${BASE_IMAGE}

LABEL maintainer="Videh Patel <videhpatel25@gmail.com>"
LABEL description="Neovim installed Dev Environment"

# Set noninteractive frontend
ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=videh
ARG USER_UID=1000
ARG USER_GID=1000

RUN set -eux; \
    if ! getent group ${USER_GID} >/dev/null; then \
        groupadd --gid ${USER_GID} ${USERNAME}; \
    else \
        existing_group=$(getent group ${USER_GID} | cut -d: -f1); \
        groupmod -n ${USERNAME} ${existing_group}; \
    fi; \
    \
    if ! getent passwd ${USER_UID} >/dev/null; then \
        useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME}; \
    else \
        existing_user=$(getent passwd ${USER_UID} | cut -d: -f1); \
        usermod -l ${USERNAME} ${existing_user}; \
        usermod -d /home/${USERNAME} -m ${USERNAME}; \
    fi; \
    \
    apt-get update && apt-get install -y sudo && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

# Install dependencies
RUN apt update && apt install -y \
    locales curl gnupg lsb-release software-properties-common \
    git \
    ninja-build \
    gettext \
    cmake \
    curl \
    build-essential \
    pkg-config \
    libtool \
    libtool-bin \
    autoconf \
    automake \
    g++ \
    unzip \
    doxygen \
    xclip \
    fd-find \
    ripgrep \
    bash-completion \
 && rm -rf /var/lib/apt/lists/*

# Get git autocompletion working
RUN cat <<'EOF' >> ~/.bashrc
if [ -f /usr/share/bash-completion/completions/git ]; then
  source /usr/share/bash-completion/completions/git
fi
EOF

# Install Node.js and npm (LTS)
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt install -y nodejs && \
    npm install -g npm@latest && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Clone Neovim and build specific version
RUN git clone https://github.com/neovim/neovim.git /neovim \
 && cd /neovim \
 && git checkout v0.11.4 \
 && make CMAKE_BUILD_TYPE=Release \
 && make install \
 && cd / \
 && rm -rf /neovim

# Install lazygit
RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') && \
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && \
    tar xf lazygit.tar.gz lazygit && \
    install lazygit /usr/local/bin && \
    rm lazygit.tar.gz lazygit

USER $USERNAME
WORKDIR /home/$USERNAME

# Set global Git username and email
RUN git config --global user.name "Videh Patel" \
 && git config --global user.email "videhpatel25@gmail.com"


# ARG NVIM_CONFIG_REPO=https://github.com/videh25/nvim_config.git
# ---- LazyVim setup ----
# Clone your LazyVim config into ~/.config/nvim
RUN git clone https://github.com/videh25/nvim_config.git ~/.config/nvim

# Install plugins automatically (LazyVim supports automatic plugin install)
RUN nvim --headless "+Lazy! sync" "+TSUpdate" +qa

# Source ROS 2 setup
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc

CMD ["bash"]
