name: Multi-Image Docker Build & Publish

# Run on push to the main branch
on:
  push:
    branches: [ main ]
  # Allows manual triggering from the GitHub Actions UI
  workflow_dispatch:

# Define environment variables used throughout the workflow
env:
  REGISTRY: ghcr.io
  # The image name uses the repository owner and name: ghcr.io/OWNER/REPO
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # The 'build' job will run multiple times based on the matrix strategy
  build_and_publish:
    runs-on: ubuntu-latest
    
    # Crucial: Give the workflow job permission to write to the container registry
    permissions:
      contents: read
      packages: write
      
    # -----------------------------------------------------------
    # 1. MATRIX STRATEGY DEFINITION
    # This defines the parameters for each concurrent run of this job.
    # -----------------------------------------------------------
    strategy:
      matrix:
        base_image:
          - name: ros:humble-ros-base-jammy
          - name: osrf/ros:humble-desktop-full-jammy
          - name: ros:jazzy-ros-base-noble
          - name: osrf/ros:jazzy-desktop-full-noble
          - name: ros:rolling-ros-base-noble
          - name: osrf/ros:rolling-desktop-full-noble
            
    # The job name will be dynamically set (e.g., "Build Development Image")
    name: Build ${{ matrix.base_image.name }} Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------------------------------
      # 2. Setup Docker Buildx
      # Recommended to ensure advanced features (like caching) are available
      # -----------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # -----------------------------------------------------------
      # 3. Log into GHCR
      # Uses the built-in GH_TOKEN to securely authenticate
      # -----------------------------------------------------------
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          
      # -----------------------------------------------------------
      # 4. Build and Push the Image
      # This step runs for EACH build_image defined in the matrix.
      # -----------------------------------------------------------
      - name: Build and push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.build_name.name }} Docker image
        uses: docker/build-push-action@v5
        with:
          # Build-time argument is passed using the matrix value
          build-args: BASE_IMAGE=${{ matrix.base_image.name }}
          
          # The Dockerfile is located in the repository root
          file: ./Dockerfile.base
          
          # Push the image to the registry (true)
          push: true
          
          # Define the tags using the matrix value
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.build_name.name }}
          # Use local cache for faster builds
          cache-from: type=local,scope=${{ matrix.base_image.name }},mode=max
          cache-to: type=local,scope=${{ matrix.base_image.name }},mode=max,compression=zstd
